server:
  port: 8081
spring:
  application:
    name: my-es-demo
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.19.10.40:8026/db_test?serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&nullNamePatternMatchesAll=true&zeroDateTimeBehavior=CONVERT_TO_NULL&tinyInt1isBit=false&autoReconnect=true&useSSL=false&pinGlobalTxToPhysicalConnection=true&characterEncoding=utf8
    username: root
    password: zrSQ7?uwA
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 20
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 172.20.140.22:9300
      cluster-name: my-application
