server:
  port: 8081
spring:
  rabbitmq:
    host: 8.129.54.157
    port: 5672
    virtual-host: my
    username: liaozijian
    password: lzj123456
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
        default-requeue-rejected: false
