server:
  port: 8082
spring:
  rabbitmq:
    host: 8.129.54.157
    port: 5672
    virtual-host: my
    username: liaozijian
    password: lzj123456
    connection-timeout: 1000000
    #开启消息确认模式
    publisher-confirms: true
    #开启消息可达监听
    publisher-returns: true
    #开启不可达消息不会被mq删除，会回调监听方法
    template:
      mandatory: true

