spring:
  application:
    name: quick-start
  redis:
    database: 0
    timeout: 5000ms
    host: 172.20.140.111
    port: 6379
    password: 123456
    lettuce:
      pool:
        min-idle: 10
        max-idle: 50
        max-active: 100
        max-wait: 5000ms

